# This workflow will build and deploy on pushes to the development branch

name: deploy-development

on:
  push:
    branches:
      - development

jobs:
#   firebase-deploy:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@master
#       - uses: actions/setup-node@master
#         with:
#           node-version: '10.x'
#       - name: Install cloud functions dependencies
#         working-directory: ./functions
#         run: npm install
#       - run: npm install
#       - run: npm run build
#       - uses: w9jds/firebase-action@master
#         with:
#           args: deploy -P trtlapps-development
#         env:
#           FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}

  app-engine-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Initialize Google Cloud SDK
        uses: zxyle/publish-gae-action@master
        with:
          service_account_email: ${{ secrets.GCP_SA_EMAIL_DEV }}
          service_account_key: ${{ secrets.GCP_SA_KEY_DEV }}
          project_id: ${{ secrets.GAE_PROJECT_ID_DEV }}
          gae_config_path: /app_engine/app-development.yaml
      - name: Build app engine project
        working-directory: ./app_engine
        run: npm run build
      - name: Publish app to Google App Engine
        working-directory: ./app_engine
        run: |
          gcloud auth activate-service-account ${{ secrets.GCP_SA_EMAIL_DEV }} --key-file=client-secret.json
          gcloud config set project ${{ secrets.GAE_PROJECT_ID_DEV }}
          gcloud -q app deploy app-development.yaml --promote
